import "oaidl.idl";
import "ocidl.idl";

[
  object,
  oleautomation,
  uuid(088C5F6E-B213-4A8E-98AD-9D64D8913968),
  helpstring("IBraveVpnService Interface"),
  pointer_default(unique)
]
interface IBraveVpnService : IUnknown
{
  HRESULT EnableVpn([in, string] const WCHAR* config);
};

[
  uuid(A0575AC4-E934-4055-B210-655CCCB40535),
  version(1.0),
  helpstring("BraveVpnService 1.0 Type Library")
]
library BraveVpnServiceLib {
  importlib("stdole2.tlb");

  interface IElevator;
};
